chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

onlineCounseling/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from counseling import views as user_views
from django.views.generic import TemplateView




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('counseling.urls')),
    path("signlog/",user_views.signlog, name="signlog"),
    path("log/",auth_views.LoginView.as_view(template_name='counseling/log.html'), name="log"),
    path("logout/",auth_views.LogoutView.as_view(template_name='counseling/base.html'), name="logout"),

    path('chat/', TemplateView.as_view(template_name="chat/home.html")),
    path('messages/', include('chat.urls')),



]

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):  # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                    first=user,
                    second=user2
                )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_success_url(self):
        return self.request.path

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Chat x Channels Rapidly</title>
    {% include 'chat/css.html' %}
</head>
<body>

<div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col'>
            <h1 class='p-0 m-0'></h1>
        </div>
    </div>
{% block content %}
{% endblock %}
</div>


{% include 'chat/js.html' %}
{% block script %}
{% endblock %}

</body>
</html>

chat/templates/chat/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Chiropractic - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'counseling/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'counseling/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'counseling/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'counseling/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'counseling/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'counseling/css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static 'counseling/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'counseling/css/style.css' %}">


  </head>
  <body>



  {% if message %}'
    {% for message in messages %}
        <div class="alert  alert-{{ message.tags }}">
            {{ message }}
        </div>

    {% endfor %}
  {% endif %}
  	<div class="top py-1">
  		<div class="container">
  			<div class="row">
	    		<div class="col d-flex align-items-center">
	    			<p class="mb-0"><a href="#">chiropractic@email.com</a> | <a href="#">Help Desk</a> | </p>
	    		</div>
	    		<div class="col-4 d-flex justify-content-end">
	    			<div class="social-media">
			    		<p class="mb-0 d-flex">
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
			    		</p>
		        </div>
	    		</div>
	    	</div>
  		</div>
  	</div>
		<div class="wrap">
	    <div class="container">
				<div class="row justify-content-between">
					<div class="col-md-3 mb-md-0 mb-4 d-flex align-items-center">
						<a class="navbar-brand" href="index.html">Chiropractic</a>
					</div>
					<div class="col-md-7">
						<div class="row">
							<div class="col-md-8 mb-md-0 mb-3">
								<div class="top-wrap d-flex">
									<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-location-arrow"></span></div>
									<div class="text"><span>Address</span><span>198 West 21th Street, Suite 721 New York NY 10016</span></div>
								</div>
							</div>
							<div class="col">
								<div class="top-wrap d-flex">
									<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-phone"></span></div>
									<div class="text"><span>Call us</span><span>(+01) 123 456 7890</span></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="fa fa-bars"></span> Menu
	      </button>
				<div class="order-lg-last">
                    {% if request.user.is_authenticated %}
                    {% else %}
          <a href="\log" class="btn btn-primary">Make an appointment</a>
                    {% endif %}
        </div>



	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">
	        	<li class="nav-item"><a href="\" class="nav-link">Home</a></li>
	        	<li class="nav-item {% block about %}{% endblock %}"><a href="\about" class="nav-link">About</a></li>
	        	<li class="nav-item {% block ProfileFilterView %}{% endblock %}"><a href="\ProfileFilterView" class="nav-link">Team</a></li>
	        	<li class="nav-item {% block services %}{% endblock %}"><a href="\services" class="nav-link">Services</a></li>
	        	<li class="nav-item {% block department %}{% endblock %}"><a href="\department" class="nav-link">Departments</a></li>
	        	<li class="nav-item {% block gallery %}{% endblock %}"><a href="\gallery" class="nav-link">Gallery</a></li>
	        	<li class="nav-item {% block blog %}{% endblock %}"><a href="\blog" class="nav-link">Blog</a></li>
	           <li class="nav-item {% block contact %}{% endblock %}"><a href="\contact" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
  <!-- nav end -->
    {% block body %} {% endblock %}
  <div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col'>
            <h1 class='p-0 m-0'></h1>
        </div>
    </div>
{% block content %}
{% endblock %}
</div>


{% include 'chat/js.html' %}
{% block script %}
{% endblock %}


    <!-- footer start -->
    <footer class="footer ftco-section ftco-no-pt">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6 col-lg">
            <div class="ftco-footer-widget py-4 py-md-5">
              <h2 class="logo"><a href="#">Chiropractic</a></h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-4">
                <li class="ftco-animate"><a href="#"><span class="fa fa-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="fa fa-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="fa fa-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-lg">
            <div class="ftco-footer-widget ml-md-5 py-5">
              <h2 class="ftco-heading-2">Services</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-1 d-block"><span class="fa fa-check mr-3"></span>Spinal Manupulation</a></li>
                <li><a href="#" class="py-1 d-block"><span class="fa fa-check mr-3"></span>Electrotherapy</a></li>
                <li><a href="#" class="py-1 d-block"><span class="fa fa-check mr-3"></span>Manual Lympahtic</a></li>
                <li><a href="#" class="py-1 d-block"><span class="fa fa-check mr-3"></span>Medical Acupuncture</a></li>
                <li><a href="#" class="py-1 d-block"><span class="fa fa-check mr-3"></span>Therapeutic Exercise</a></li>
                <li><a href="#" class="py-1 d-block"><span class="fa fa-check mr-3"></span>Joint Mobilization</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-lg">
            <div class="ftco-footer-widget py-4 py-md-5">
            	<h2 class="ftco-heading-2">Contact information</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon fa fa-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon fa fa-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon fa fa-paper-plane"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md-6 col-lg">
             <div class="ftco-footer-widget bg-primary p-4 py-5">
              <h2 class="ftco-heading-2">Business Hours</h2>
              <div class="opening-hours">
              	<h4>Opening Days:</h4>
              	<p class="pl-3">
              		<span>Monday – Friday : 9am to 20 pm</span>
              		<span>Saturday : 9am to 17 pm</span>
              	</p>
              	<h4>Vacations:</h4>
              	<p class="pl-3">
              		<span>All Sunday Days</span>
              		<span>All Official Holidays</span>
              	</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  {% load static %}
  <script src="{% static 'counseling/js/jquery.min.js'  %}"></script>
  <script src="{% static 'counseling/js/jquery-migrate-3.0.1.min.js'  %}"></script>
  <script src="{% static 'counseling/js/popper.min.js'  %}"></script>
  <script src="{% static 'counseling/js/bootstrap.min.js'  %}"></script>
  <script src="{% static 'counseling/js/jquery.easing.1.3.js'  %}"></script>
  <script src="{% static 'counseling/js/jquery.waypoints.min.js'  %}"></script>
  <script src="{% static 'counseling/js/jquery.stellar.min.js'  %}"></script>
  <script src="{% static 'counseling/js/jquery.animateNumber.min.js'  %}"></script>
  <script src="{% static 'counseling/js/bootstrap-datepicker.js'  %}"></script>
  <script src="{% static 'counseling/js/jquery.timepicker.min.js'  %}"></script>
  <script src="{% static 'counseling/js/owl.carousel.min.js'  %}"></script>
  <script src="{% static 'counseling/js/jquery.magnific-popup.min.js'  %}"></script>
  <script src="{% static 'counseling/js/scrollax.min.js'  %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'counseling/js/google-map.js'  %}"></script>
  <script src="{% static 'counseling/js/main.js'  %}"></script>

  </body>
</html>

chat/templates/chat/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">l>

chat/templates/chat/home.html
{% extends "chat/base.html" %}

{% block content %}

<p class='lead'>Welcome Home</p>
{% endblock %}

chat/templates/chat/inbox.html
{% extends "chat/base2.html" %}

{% block content %}


{% endblock %}

chat/templates/chat/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

chat/templates/chat/thread.html
{% extends "chat/base2.html" %}

{% block content %}
<h3>Chat with - {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}

<li>{{ chat.message }} via {{ chat.user }}</li>

{% endfor %}
</ul>


<form id='form' method='POST'> {% csrf_token %}
    <input type="hidden" id="myUsername" value="{{user.username}}"/>
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>
<script>
// websocket scripts
//console.log(window.location)
var loc = window.location
var formData= $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")
var me = $("#myUsername").val()

var wsStart = 'ws://'
if (loc.protocol == 'https:'){
    wsStart = 'wss//'
}
var endpoint = wsStart+loc.host+loc.pathname
var socket = new WebSocket(endpoint)


socket.onmessage = function(e){
    console.log("message",e)
    var chatDataMsg = JSON.parse(e.data)
    chatHolder.append("<li>" + chatDataMsg.message + "via" + chatDataMsg.username + "</li>")

}
socket.onopen = function(e){
    console.log("open",e)
    formData.submit(function(event){
        event.preventDefault()
        var msgText = msgInput.val()
        //chatHolder.append("<li>" + msgText + " via " + me +"</li>")
        //Var formDataSerialized = formData.serialize()
        var finalData = {
            'message': msgText
        }
        socket.send(JSON.stringify(finalData))
        formData[0].reset()
    })
}
socket.onerror = function(e){
    console.log("error",e)
}
socket.onclose = function(e){
    console.log("close",e)
}



</script>
{% endblock %}